=== p6666666666/rpc/rpcclass/prpc-framework/prpc-core/src/main/java/com/czp/builder/xml/prpc-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT configuration ANY>


        <!ELEMENT port ANY>
        <!ELEMENT appName ANY>

        <!ELEMENT registry EMPTY>
        <!ATTLIST registry
                url CDATA #REQUIRED
                >

        <!ELEMENT serializer EMPTY>
        <!ATTLIST serializer
                class CDATA #REQUIRED
                name CDATA #REQUIRED
                code CDATA #REQUIRED
                >
        <!ELEMENT serializeType EMPTY>
        <!ATTLIST serializeType
                type CDATA #REQUIRED
                >

        <!ELEMENT compressor EMPTY>
        <!ATTLIST compressor
                class CDATA #REQUIRED
                name CDATA #REQUIRED
                code CDATA #REQUIRED
                >
        <!ELEMENT compressType EMPTY>
        <!ATTLIST compressType
                type CDATA #REQUIRED
                >

        <!ELEMENT loadBalancer EMPTY>
        <!ATTLIST loadBalancer
                class CDATA #REQUIRED
                >
        <!ELEMENT loadBalancerType EMPTY>
        <!ATTLIST loadBalancerType
                type CDATA #REQUIRED
                >

        <!ELEMENT idGenerator EMPTY>
        <!ATTLIST idGenerator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                machineId CDATA #REQUIRED
                >

=== p6666666666/rpc/rpcclass/prpc-demo/prpc-provider-demo/src/main/resources/prpc.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "prpc-config.dtd">
<configuration>
    <port>8096</port>
    <appName>prpc-default-appName</appName>
    <registry url="zookeeper://192.168.200.128:2181"/>
    <!-- 二选一 -->
    <serializeType type="hessian"/>
    <serializer code="3" name="hession" class="com.czp.serializer.impl.HessianSerializer"/>

    <!-- 二选一 -->
    <compressType type="gzip"/>
    <compressor code="1" name="gzip"  class="com.czp.compress.impl.GzipCompressor"/>

    <!-- 二选一 -->
    <loadBalancerType type="minimumResponseTime"/>
    <loadBalancer class="com.czp.loadbalancer.impl.MinimumResponseTimeLoadBalancer"/>


    <idGenerator class="com.czp.IdGenerator" dataCenterId="2" machineId="4"/>
</configuration>
